CLIENT_TARGET=client
SERVER_TARGET=server
CLIENT_SRC=client.c
SERVER_SRC=server.c
CLIENT_LIB=client_lib.c
SERVER_LIB=server_lib.c


CLIENT_BIN_DIR= ./client/bin
CLIENT_SRC_DIR=./client/src
CLIENT_TMP_DIR=./client/tmp

SERVER_BIN_DIR= ./server/bin
SERVER_SRC_DIR= ./server/src
SERVER_TMP_DIR= ./server/tmp

BUILD_FLAGS = -Wall
CFLAGS = -Wall -c
CLIENT_OBJ= $(CLIENT_TMP_DIR)/client.o
CLIENT_LIB_OBJ= $(CLIENT_TMP_DIR)/client_lib.o
SERVER_OBJ= $(SERVER_TMP_DIR)/server.o
SERVER_LIB_OBJ= $(SERVER_TMP_DIR)/server_lib.o
CC=gcc

$(CLIENT_TARGET): dirs $(CLIENT_OBJ)
	$(CC) $(BUILD_FLAGS) -o $(CLIENT_BIN_DIR)/$(CLIENT_TARGET) $(CLIENT_OBJ) $(CLIENT_LIB_OBJ)

$(SERVER_TARGET): dirs $(SERVER_OBJ)
	$(CC) $(BUILD_FLAGS) -o $(SERVER_BIN_DIR)/$(SERVER_TARGET) $(SERVER_OBJ) $(SERVER_LIB_OBJ)

$(CLIENT_OBJ): $(CLIENT_SRC_DIR)/$(CLIENT_SRC) $(CLIENT_SRC_DIR)/$(CLIENT_LIB)
	$(CC) $(CFLAGS) -o $(CLIENT_OBJ) $(CLIENT_SRC_DIR)/$(CLIENT_SRC)
	$(CC) $(CFLAGS) -o $(CLIENT_LIB_OBJ) $(CLIENT_SRC_DIR)/$(CLIENT_LIB)

$(SERVER_OBJ): $(SERVER_SRC_DIR)/$(SERVER_SRC) $(SERVER_SRC_DIR)/$(SERVER_LIB)
	$(CC) $(CFLAGS) -o $(SERVER_OBJ) $(SERVER_SRC_DIR)/$(SERVER_SRC)
	$(CC) $(CFLAGS) -o $(SERVER_LIB_OBJ) $(SERVER_SRC_DIR)/$(SERVER_LIB)

build: dirs $(CLIENT_TARGET) $(SERVER_TARGET)

dirs:
	mkdir -p $(CLIENT_BIN_DIR) $(SERVER_BIN_DIR) $(SERVER_TMP_DIR) $(CLIENT_TMP_DIR)
clean:
	rm -rf $(CLIENT_BIN_DIR) $(SERVER_BIN_DIR) $(SERVER_TMP_DIR) $(CLIENT_TMP_DIR)
